config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :dogs do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[show update]
  resource :dashboard
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  enum status: [ :pending, :accepted, :rejected ]
  before_create :set_total_price
  belongs_to :user
  belongs_to :dog
  has_many :reviews

  def set_total_price
    self.total_price = (self.end_date - self.start_date) * self.dog.price
  end
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :reviews, through: :bookings
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dogs, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new
  end

  def create
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new(booking_params)
    @booking.dog = @dog
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      redirect
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(status: params[:booking][:status])
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @bookings = Booking.where(user: current_user)
    @my_doggies = Booking.where(dog: current_user.dogs)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  def index
    @dogs = Dog.all.order(created_at: :asc)

    @markers = @dogs.geocoded.map do |dog|
      {
        lat: dog.latitude,
        lng: dog.longitude,
        info_window: render_to_string(partial: "info_window", locals: { dog: dog }),
        image_url: helpers.asset_url('huella.png')
      }
    end
  end

  def show
    @booking = Booking.new
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    if @dog.save
      redirect_to dog_path(@dog)
    else
      render :new
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :breed, :age, :size, :description, :price, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%# <div class="booking-container">
  <h1>Create your doggy experience</h1>

  <%= simple_form_for [ @dog, @booking ] do |f| %>
    <%# <%= f.input :start_date, as: :date, order: [:day, :month, :year] %>
    <%# <%= f.input :end_date, as: :date, order: [:day, :month, :year] %>
    <%# <%= f.submit "Submit", class: "btn-main" %>
  <%# <% end %>
<%# </div> %>

app/views/bookings/show.html.erb
<% flash[:notice] = "Your booking has been made and confirmation is pending" %>
<div class="container">
  <h4><%= "Booking with #{@booking.dog.name}" %></h4><br>



<table class="table">
  <thead>
    <tr>
      <th scope="col">Dog</th>
      <th scope="col">Date</th>
      <th scope="col">Status</th>
      <th scope="col">Total price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @booking.dog.name %></td>
      <td><%= "#{@booking.start_date.day}-#{@booking.start_date.month}-#{@booking.start_date.year} to #{@booking.end_date.day}-#{@booking.end_date.month}-#{@booking.end_date.year}"  %></td>
      <td><%= @booking.status %></td>
      <td><%= "#{@booking.total_price}€" %></td>
    </tr>

  </tbody>
</table>

</div>

app/views/dashboards/show.html.erb
<div class="table-container">
  <h1>Your bookings</h1>
  <div class="booking-message">
    <% if @bookings.empty? %>
      <%= "You currently have no bookings" %>
    <% end %>
  </div>
  <% @bookings.each do |booking|%>
    <div class="container">
      <table class="table dashboard-table">
        <thead>
          <tr>
            <th scope="col">Dog</th>
            <th scope="col">Date</th>
            <th scope="col">Status</th>
            <th scope="col">Total price</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= booking.dog.name %></td>
            <td><%= "#{booking.start_date.day}-#{booking.start_date.month}-#{booking.start_date.year} to #{booking.end_date.day}-#{booking.end_date.month}-#{booking.end_date.year}"  %></td>
            <td><%= booking.status %></td>
            <td><%= "#{booking.total_price}€" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  <% end %>

  <% @my_doggies.each do |dog_booking| %>
  <h1><%= dog_booking.dog.name %></h1>
    <div class="container">
      <table class="table dashboard-table">
        <thead>
          <tr>
            <th scope="col">Dog</th>
            <th scope="col">Date</th>
            <th scope="col">Status</th>
            <th scope="col">Total price</th>
            <th scope="col">Accept/Reject</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= dog_booking.dog.name %></td>
            <td><%= "#{dog_booking.start_date.day}-#{dog_booking.start_date.month}-#{dog_booking.start_date.year} to #{dog_booking.end_date.day}-#{dog_booking.end_date.month}-#{dog_booking.end_date.year}"  %></td>
            <td><%= dog_booking.status %></td>
            <td><%= "#{dog_booking.total_price}€" %></td>
            <td id="button-td"><%=link_to "Accept", booking_path(dog_booking, booking: {status: "accepted"}), method: :patch, class:"btn-main", id:"accept"%>
            <%=link_to "Reject", booking_path(dog_booking, booking: {status: "rejected"}), method: :patch, class:"btn-main", id:"reject"%> </td>

          </tr>
        </tbody>
      </table>
    </div>

  <% end %>
</div>

app/views/dogs/_info_window.html.erb
<h2><%= dog.name %></h2>
<p><%= dog.address %></p>
<% dog.photos.each do |photo| %>
  <%= cl_image_tag photo.key, class: "marker-image" %>
<% end %>

app/views/dogs/index.html.erb
<div>
  <h2 style="text-align: center;"> Find your next Pawnr</h2>
  <%= link_to 'Add a pawnr', new_dog_path, class: "btn-main-add-pawnr"%>
</div>

<div class="main-container">
  <div class ="cards-container" >
    <div class ="cards">
      <% @dogs.each do |dog| %>
        <%= link_to dog_path(dog) do %>
          <div class="card">
              <% if dog.photos.attached?  %>
                <div class="background" style = "background:url(<%=url_for(dog.photos.first)%>); background-size: 100% 100%; ">
                </div>
              <% end %>
            <div class= "card-body">
              <div class ='main-info'>
                <h4> <%= dog.name %></h4>
                  <div class='extra-info'>
                    <span class='price' ><%= dog.price %>€  /day</span>
                  </div>
              </div>

            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
   <div id="map"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>
</div>

app/views/dogs/new.html.erb
<div class="form-container">
  <div class="form">
    <h1>Share the puppy love</h1>
      <%= simple_form_for [ @user, @dog ], html: {class: "grid"} do |f| %>
        <div class="row">
          <div class="col-6">
            <%= f.input :name, placeholder: "Nolan" %>
          </div>
          <div class="col-6">
            <%= f.input :breed, placeholder: "American Staffordshire" %>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <%= f.input :age %>
          </div>
          <div class="col-4">
            <%= f.input :size, as: :select,  collection: ["Small", "Medium", "Large", "Extra-Large"], placeholder: "small" %>
          </div>
          <div class="col-4">
            <%= f.input :price %>
          </div>
        </div>
        <%= f.input :address, placeholder: "Carrer de Joaquim Ruyra, 9", id: "dog_address" %>
        <%= f.input :description, as: :text, placeholder: "Playful dog, loves stealing other people's food" %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }  %>
        <%= f.submit "Submit", class: "btn-main-submit" %>
      <% end %>
    </div>
  <img src="https://images.pexels.com/photos/1390361/pexels-photo-1390361.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="Someone cuddling a dog">
</div>

app/views/dogs/show.html.erb
<h1 class = "header"> My Name is <%= @dog.name %></h1>

<div class="show-top">

  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <% @dog.photos.each do |photo| %>
        <%if photo == @dog.photos.first %>
            <div class="carousel-item active">
              <%= cl_image_tag photo.key, crop: :fill, class:"d-block w-100"%>
            </div>
        <% else %>
            <div class="carousel-item ">
            <%= cl_image_tag photo.key, crop: :fill, class:"d-block w-100"%>
            </div>
          <% end %>
        <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="book">
          <h1>Create your doggy experience</h1>

            <%= simple_form_for [ @dog, @booking ] do |f| %>
              <%= f.input :start_date, as: :date, order: [:day, :month, :year] %>
              <%= f.input :end_date, as: :date, order: [:day, :month, :year] %>
              <div class="price">
                <%= f.submit "Submit", class: "btn-main" %>
                <h5 class = "euro"><%= "#{@dog.price}€ / day" %></h5>
              </div>
          <% end %>
  </div>

</div>


  <div class="about-me mx-auto">
    <div class="description-details col-8">
      <h2 class="text-center"> About Me </h2>
      <p class = "dog-description"> <%= "#{@dog.name} is a beautiful and very calm dog.
          She loves playing with other dogs. She rarely barks and her favorite food is bacon"%></p>
   </div>

     <div class= "right">
        <div class = "list-details">
          <ul class = 'details'>
            <li class="d-flex"><strong class="mr-2">Breed: </strong> <%= @dog.breed%> </li>
            <li><strong>Size:</strong> <%= @dog.size%> </li>
            <li><strong>Gender:</strong> Female </li>
            <li><strong>Age:</strong> <%= @dog.age%></li>
          </ul>
        </div>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pawnr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <%= favicon_link_tag 'huella.png' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>

      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Pawnr</title>
  <link rel="shortcut icon" href="data:image/x-icon;" type="image/x-icon">
  <!-- We need this line below for responsiveness! -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Open+Sans:wght@300&display=swap"
  rel="stylesheet">
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <!-- code a Hero / Banner section -->
<div class="banner">
  <div class="container">
    <h1>Meet your new pawnr</h1>
    <p>Find a dog to spend the day with</p>
    <%= link_to "Find a pawnr", dogs_path, class: "btn-main"%>
  </div>
</div>
<h2><strong>Explore the possibilities</strong></h2>
  <div class="container">


    <div class="services-list" role="list">

      <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-0" role="listitem">
        <%= image_tag "walk.png", class: "avatar-walk", alt: "avatar-large" %>
          <div class="service-row"><i class="rover-icon rover-icon-sitter-home service-icon"></i>
            <div class="description">
              <label class="title">Dog walks</label>
              <div class="content text-muted">Spend 30 or 60 minutes walking around the neighborhood.</div>
            </div>
          </div>
      </div>

      <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-0" role="listitem">
        <%= image_tag "hosting.png", class: "avatar-hosting", alt: "avatar-large" %>
          <div class="service-row"><i class="rover-icon rover-icon-sitter-traveling service-icon"></i>
            <div class="description">
              <label class="title">Hosting in your home</label>
              <div class="content text-muted">Live the full experience of dog sitting: Host a Pawnr in your home.</div>
            </div>
          </div>
      </div>

      <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-0" role="listitem">
        <%= image_tag "daycare.png", class: "avatar-daycare", alt: "avatar-large" %>
      <div class="service-row"><i class="rover-icon rover-icon-walking service-icon"></i>
        <div class="description">
          <label class="title">Doggy day care</label>
          <div class="content text-muted">Take care of your Pawnr for a couple of hours during the day.</div>
        </div>
      </div>
    </div>

  </div>

      <div class="card-category" style="background-image">
      <div class="card-testimonial">
        <div class="card-block">
          <hr class="card-block-border">
          <div class="card-text">
            <h3 class="thin-text">


              <span>

                  "I love dogs, but since I go to the office everyday, I can't have my own dog; Pawnr allows me to spend my weekends with puppies." &nbsp;

               </span>
              <br>
              <span class="customer-name"><span class="hidden-xs">–&nbsp;</span><span><strong>Carla F.</strong></span></span>
            </h3>
            <div class="dog-people">
              <span>

                We’re The Dog People.&nbsp;

<!-- this space intentionally left blank-->

              </span>
            </div>
            <div role="img" aria-label="Woman in the park with a dog"></div>
          </div>
        </div>
      </div>

  </div>
</div>

  <!-- code a "How it works" section -->

</body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">

    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      © 2021 Pawnr, Inc. All rights reserved. Barcelona, Catalonia <i class="fas fa-heart"></i>
    </div>
    <%= link_to (image_tag "dog-footer.png"), root_path, class: "footer-image" %>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-pawnr">
  <%= link_to (image_tag "logo.png"), root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/Dianabarr19", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Add a dog", new_dog_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>